import { motion } from "framer-motion"
import { Link } from "react-router-dom"
import {
    BarChart3, ArrowRight, TrendingUp, TrendingDown, Activity, Clock,
    Users, MessageSquare, Brain, Target, Zap, CheckCircle, AlertTriangle,
    Calendar, Download, FileText, ArrowUpRight, Eye, Shield, Sparkles,
    PieChart, LineChart, Timer, Award, DollarSign, Percent
} from "lucide-react"
import { Button } from "../../components/ui/Button"
import { usePageTitle } from "../../hooks/usePageTitle"

const kpiCards = [
    { label: "Auto-Resolve Rate", value: "73%", trend: "+8%", up: true, target: "70%", icon: Zap },
    { label: "Avg Response Time", value: "45s", trend: "-12s", up: true, target: "<60s", icon: Timer },
    { label: "Containment Rate", value: "78%", trend: "+5%", up: true, target: "70%", icon: Target },
    { label: "CSAT Score", value: "4.6", trend: "+0.3", up: true, target: "4.5", icon: Award }
]

const aiMetrics = [
    { label: "Total Suggestions", value: "12,847", desc: "Generated by AI Copilot" },
    { label: "Usage Rate", value: "68%", desc: "Suggestions used by agents" },
    { label: "Edit Rate", value: "23%", desc: "Suggestions edited before sending" },
    { label: "Active Agents", value: "24", desc: "Using Copilot this week" }
]

const channels = [
    { name: "WhatsApp", value: 42, color: "#25D366" },
    { name: "Email", value: 28, color: "#EA4335" },
    { name: "Instagram", value: 15, color: "#E4405F" },
    { name: "Live Chat", value: 12, color: "#FACC15" },
    { name: "Telegram", value: 3, color: "#0088CC" }
]

const differentiators = [
    { title: "Real-Time Intelligence", desc: "Live dashboard updates every 30 seconds via subscriptions", icon: Activity },
    { title: "AI-First Analytics", desc: "Deep visibility into AI performance, not just volume metrics", icon: Brain },
    { title: "Actionable Insights", desc: "AI-generated recommendations for improvements", icon: Sparkles },
    { title: "Revenue Attribution", desc: "Connect support conversations to business outcomes", icon: DollarSign },
    { title: "Goal Tracking", desc: "Progress bars toward targets (70% containment, 95% SLA)", icon: Target },
    { title: "Export Ready", desc: "CSV and PDF exports for stakeholder reporting", icon: Download }
]

export function Analytics() {
    usePageTitle("Analytics - Performance Insights & Metrics")
    return (
        <div className="pt-32 pb-20 relative overflow-hidden">
            {/* Ambient Background Glow */}
            <div className="fixed top-0 left-1/2 -translate-x-1/2 w-full h-[600px] bg-[radial-gradient(ellipse_80%_50%_at_50%_-20%,rgba(251,146,60,0.3),rgba(255,255,255,0))] pointer-events-none z-0" />

            {/* Hero Section */}
            <section className="max-w-7xl mx-auto px-6 mb-32 relative z-10">
                <div className="grid lg:grid-cols-2 gap-12 items-center">
                    <motion.div
                        initial={{ opacity: 0, x: -20 }}
                        animate={{ opacity: 1, x: 0 }}
                        transition={{ duration: 0.6 }}
                    >
                        <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-orange-500/10 border border-orange-500/20 mb-6">
                            <BarChart3 className="w-4 h-4 text-orange-400" />
                            <span className="text-sm text-orange-400">Analytics</span>
                        </div>
                        <h1 className="text-5xl md:text-6xl font-medium tracking-tighter leading-[1.1] mb-6 bg-clip-text text-transparent bg-gradient-to-b from-white to-white/60">
                            See everything.<br />
                            Improve faster.
                        </h1>
                        <p className="text-xl text-gray-400 mb-8 leading-relaxed">
                            Real-time dashboards, AI performance tracking, revenue attribution, and actionable insights.
                            Turn data into decisions with comprehensive analytics.
                        </p>
                        <div className="flex flex-wrap gap-4">
                            <a href="https://app.enorve.com/">
                                <Button variant="primary" size="lg">
                                    Get Started
                                    <ArrowRight className="w-5 h-5 ml-2" />
                                </Button>
                            </a>
                            <Link to="/contact-sales">
                                <Button variant="secondary" size="lg">
                                    Talk to sales
                                </Button>
                            </Link>
                        </div>
                    </motion.div>

                    {/* Interactive Dashboard Mockup */}
                    <motion.div
                        initial={{ opacity: 0, x: 20 }}
                        animate={{ opacity: 1, x: 0 }}
                        transition={{ duration: 0.6, delay: 0.2 }}
                        className="relative hidden md:block"
                    >
                        <div className="relative">
                            {/* Glow Effect */}
                            <div className="absolute -bottom-20 left-1/2 -translate-x-1/2 w-[80%] h-48 bg-orange-500/25 blur-[120px] -z-10" />

                            {/* Main Dashboard UI */}
                            <div className="rounded-2xl overflow-hidden border border-white/10 shadow-[0_40px_140px_rgba(0,0,0,0.85)] bg-[#0C0E12]">
                                {/* Header */}
                                <div className="flex items-center justify-between px-5 py-3 border-b border-white/10 bg-white/[0.02]">
                                    <div className="flex items-center gap-2">
                                        <div className="flex gap-1.5">
                                            <div className="w-2.5 h-2.5 rounded-full bg-red-500/20 border border-red-500/40" />
                                            <div className="w-2.5 h-2.5 rounded-full bg-yellow-500/20 border border-yellow-500/40" />
                                            <div className="w-2.5 h-2.5 rounded-full bg-green-500/20 border border-green-500/40" />
                                        </div>
                                        <span className="text-xs text-gray-500 ml-3">Analytics Dashboard</span>
                                    </div>
                                    <div className="flex items-center gap-2">
                                        <div className="flex items-center gap-1 px-2 py-1 rounded bg-green-500/10 border border-green-500/20">
                                            <div className="w-1.5 h-1.5 rounded-full bg-green-500 animate-pulse" />
                                            <span className="text-[10px] text-green-400">Live</span>
                                        </div>
                                        <div className="flex items-center gap-1 px-2 py-1 rounded bg-white/5 text-gray-500">
                                            <Calendar className="w-3 h-3" />
                                            <span className="text-[10px]">Last 7 days</span>
                                        </div>
                                    </div>
                                </div>

                                {/* KPI Row */}
                                <div className="grid grid-cols-4 gap-3 p-4 border-b border-white/5">
                                    {[
                                        { label: "Conversations", value: "2,847", change: "+12%", up: true },
                                        { label: "Auto-Resolved", value: "73%", change: "+8%", up: true },
                                        { label: "Avg Response", value: "45s", change: "-12s", up: true },
                                        { label: "CSAT", value: "4.6/5", change: "+0.3", up: true }
                                    ].map((kpi) => (
                                        <div key={kpi.label} className="p-3 rounded-lg bg-white/[0.02] border border-white/5">
                                            <div className="text-[10px] text-gray-500 mb-1">{kpi.label}</div>
                                            <div className="flex items-end gap-2">
                                                <span className="text-lg font-bold text-white">{kpi.value}</span>
                                                <span className={`text-[10px] ${kpi.up ? 'text-green-400' : 'text-red-400'}`}>
                                                    {kpi.change}
                                                </span>
                                            </div>
                                        </div>
                                    ))}
                                </div>

                                {/* Chart Area */}
                                <div className="p-4">
                                    <div className="flex items-center justify-between mb-3">
                                        <span className="text-xs text-white font-medium">Conversation Volume</span>
                                        <div className="flex gap-2">
                                            <span className="text-[10px] px-2 py-0.5 rounded bg-orange-500/10 text-orange-400">Messages</span>
                                            <span className="text-[10px] px-2 py-0.5 rounded bg-white/5 text-gray-500">Conversations</span>
                                        </div>
                                    </div>

                                    {/* Simulated Chart */}
                                    <div className="h-32 flex items-end gap-1">
                                        {[40, 65, 45, 80, 55, 90, 70, 85, 60, 95, 75, 88].map((height, i) => (
                                            <div key={i} className="flex-1 flex flex-col gap-0.5">
                                                <div
                                                    className="rounded-t bg-gradient-to-t from-orange-500/40 to-orange-500/80 transition-all hover:from-orange-500/60 hover:to-orange-400"
                                                    style={{ height: `${height}%` }}
                                                />
                                            </div>
                                        ))}
                                    </div>
                                    <div className="flex justify-between mt-2 text-[10px] text-gray-500">
                                        <span>Mon</span>
                                        <span>Tue</span>
                                        <span>Wed</span>
                                        <span>Thu</span>
                                        <span>Fri</span>
                                        <span>Sat</span>
                                        <span>Sun</span>
                                    </div>
                                </div>

                                {/* Bottom Stats */}
                                <div className="grid grid-cols-3 gap-3 p-4 border-t border-white/5">
                                    <div className="flex items-center gap-2">
                                        <div className="w-8 h-8 rounded-lg bg-green-500/10 flex items-center justify-center">
                                            <Brain className="w-4 h-4 text-green-400" />
                                        </div>
                                        <div>
                                            <div className="text-[10px] text-gray-500">AI Handled</div>
                                            <div className="text-xs text-white font-medium">78%</div>
                                        </div>
                                    </div>
                                    <div className="flex items-center gap-2">
                                        <div className="w-8 h-8 rounded-lg bg-blue-500/10 flex items-center justify-center">
                                            <Users className="w-4 h-4 text-blue-400" />
                                        </div>
                                        <div>
                                            <div className="text-[10px] text-gray-500">Agent Handled</div>
                                            <div className="text-xs text-white font-medium">22%</div>
                                        </div>
                                    </div>
                                    <div className="flex items-center gap-2">
                                        <div className="w-8 h-8 rounded-lg bg-orange-500/10 flex items-center justify-center">
                                            <DollarSign className="w-4 h-4 text-orange-400" />
                                        </div>
                                        <div>
                                            <div className="text-[10px] text-gray-500">Revenue</div>
                                            <div className="text-xs text-white font-medium">₹8.4L</div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            {/* Floating Elements */}
                            <div className="absolute -right-4 top-8 bg-[#0C0E12] border border-white/10 rounded-lg p-3 shadow-xl animate-float">
                                <div className="flex items-center gap-2">
                                    <TrendingUp className="w-4 h-4 text-green-400" />
                                    <div>
                                        <div className="text-xs text-white">+23%</div>
                                        <div className="text-[10px] text-gray-500">vs last week</div>
                                    </div>
                                </div>
                            </div>

                            <div className="absolute -left-4 bottom-12 bg-[#0C0E12] border border-white/10 rounded-lg p-3 shadow-xl animate-float" style={{ animationDelay: '1s' }}>
                                <div className="flex items-center gap-2">
                                    <Activity className="w-4 h-4 text-orange-400" />
                                    <span className="text-xs text-white">Real-time</span>
                                </div>
                            </div>
                        </div>
                    </motion.div>
                </div>
            </section>

            {/* KPI Cards Section */}
            <section className="py-24 relative bg-black/50">
                <div className="max-w-[1200px] mx-auto px-6">
                    <div className="flex flex-col lg:flex-row lg:items-end justify-between mb-16 gap-8">
                        <motion.h2
                            initial={{ opacity: 0, y: 20 }}
                            whileInView={{ opacity: 1, y: 0 }}
                            transition={{ duration: 0.6 }}
                            viewport={{ once: true }}
                            className="text-4xl md:text-6xl font-medium text-white tracking-tighter leading-[1.1]"
                        >
                            Track what<br />matters
                        </motion.h2>
                        <motion.div
                            initial={{ opacity: 0, y: 20 }}
                            whileInView={{ opacity: 1, y: 0 }}
                            transition={{ duration: 0.6, delay: 0.1 }}
                            viewport={{ once: true }}
                            className="text-xl text-gray-400 leading-relaxed max-w-lg"
                        >
                            Core KPIs with goal tracking, trend analysis, and month-over-month comparisons at a glance.
                        </motion.div>
                    </div>

                    <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
                        {kpiCards.map((kpi, index) => (
                            <motion.div
                                key={kpi.label}
                                initial={{ opacity: 0, y: 20 }}
                                whileInView={{ opacity: 1, y: 0 }}
                                transition={{ duration: 0.5, delay: index * 0.1 }}
                                viewport={{ once: true }}
                                className="group p-6 rounded-[24px] bg-[#0C0E12] border border-white/5 hover:border-orange-500/30 transition-all duration-500"
                            >
                                <div className="flex items-center justify-between mb-4">
                                    <div className="w-12 h-12 rounded-xl bg-orange-500/10 flex items-center justify-center group-hover:scale-110 transition-transform duration-500">
                                        <kpi.icon className="w-6 h-6 text-orange-400" />
                                    </div>
                                    <div className={`flex items-center gap-1 px-2 py-1 rounded ${kpi.up ? 'bg-green-500/10 text-green-400' : 'bg-red-500/10 text-red-400'}`}>
                                        {kpi.up ? <TrendingUp className="w-3 h-3" /> : <TrendingDown className="w-3 h-3" />}
                                        <span className="text-xs">{kpi.trend}</span>
                                    </div>
                                </div>
                                <div className="text-3xl font-bold text-white mb-1">{kpi.value}</div>
                                <div className="text-sm text-gray-500 mb-3">{kpi.label}</div>
                                <div className="flex items-center gap-2">
                                    <div className="flex-1 h-2 rounded-full bg-white/10 overflow-hidden">
                                        <div
                                            className="h-full rounded-full bg-gradient-to-r from-orange-500 to-amber-500"
                                            style={{ width: `${parseInt(kpi.value)}%` }}
                                        />
                                    </div>
                                    <span className="text-[10px] text-gray-500">Target: {kpi.target}</span>
                                </div>
                            </motion.div>
                        ))}
                    </div>
                </div>
            </section>

            {/* AI Performance Analytics */}
            <section className="py-24 relative z-10">
                <div className="max-w-[1200px] mx-auto px-6">
                    <div className="text-center mb-16">
                        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-violet-500/10 border border-violet-500/20 mb-4">
                            <Brain className="w-3 h-3 text-violet-400" />
                            <span className="text-xs text-violet-400 font-medium">AI Performance</span>
                        </div>
                        <motion.h2
                            initial={{ opacity: 0, y: 20 }}
                            whileInView={{ opacity: 1, y: 0 }}
                            transition={{ duration: 0.6 }}
                            viewport={{ once: true }}
                            className="text-4xl md:text-5xl font-medium text-white tracking-tighter mb-4"
                        >
                            AI Performance Analytics
                        </motion.h2>
                        <motion.p
                            initial={{ opacity: 0, y: 20 }}
                            whileInView={{ opacity: 1, y: 0 }}
                            transition={{ duration: 0.6, delay: 0.1 }}
                            viewport={{ once: true }}
                            className="text-lg text-gray-400 max-w-2xl mx-auto"
                        >
                            Deep visibility into AI effectiveness, containment rates, confidence distribution, and escalation patterns.
                        </motion.p>
                    </div>

                    <div className="grid lg:grid-cols-2 gap-6">
                        {/* Containment & Effectiveness */}
                        <motion.div
                            initial={{ opacity: 0, x: -20 }}
                            whileInView={{ opacity: 1, x: 0 }}
                            transition={{ duration: 0.6 }}
                            viewport={{ once: true }}
                            className="p-6 rounded-[32px] bg-[#0C0E12] border border-white/5"
                        >
                            <h3 className="text-lg font-medium text-white mb-6">Containment Rate</h3>

                            <div className="flex items-center justify-between mb-4">
                                <div>
                                    <div className="text-4xl font-bold text-white">78%</div>
                                    <div className="text-sm text-gray-500">Auto-resolved ÷ AI-handled</div>
                                </div>
                                <div className="text-right">
                                    <div className="text-sm text-green-400 flex items-center gap-1 justify-end">
                                        <TrendingUp className="w-4 h-4" />
                                        +5% vs last week
                                    </div>
                                    <div className="text-xs text-gray-500 mt-1">Target: 70%</div>
                                </div>
                            </div>

                            {/* Progress to target */}
                            <div className="mb-6">
                                <div className="h-4 rounded-full bg-white/10 overflow-hidden relative">
                                    <div className="absolute h-full w-[70%] border-r-2 border-dashed border-white/20" />
                                    <div className="h-full w-[78%] rounded-full bg-gradient-to-r from-violet-500 to-purple-500" />
                                </div>
                                <div className="flex justify-between mt-2 text-xs">
                                    <span className="text-gray-500">0%</span>
                                    <span className="text-gray-500">70% target</span>
                                    <span className="text-gray-500">100%</span>
                                </div>
                            </div>

                            {/* Confidence Distribution */}
                            <div className="p-4 rounded-xl bg-white/[0.02] border border-white/5">
                                <div className="text-xs text-gray-500 mb-3">Confidence Distribution</div>
                                <div className="space-y-2">
                                    {[
                                        { range: "90-100%", count: 892, percent: 45, color: "#10B981" },
                                        { range: "70-90%", count: 456, percent: 23, color: "#3B82F6" },
                                        { range: "50-70%", count: 312, percent: 16, color: "#F59E0B" },
                                        { range: "0-50%", count: 287, percent: 16, color: "#EF4444" }
                                    ].map((item) => (
                                        <div key={item.range} className="flex items-center gap-3">
                                            <span className="text-[10px] text-gray-400 w-16">{item.range}</span>
                                            <div className="flex-1 h-2 rounded-full bg-white/10 overflow-hidden">
                                                <div
                                                    className="h-full rounded-full"
                                                    style={{ width: `${item.percent}%`, backgroundColor: item.color }}
                                                />
                                            </div>
                                            <span className="text-[10px] text-gray-500 w-10">{item.count}</span>
                                        </div>
                                    ))}
                                </div>
                            </div>
                        </motion.div>

                        {/* Escalation Analysis */}
                        <motion.div
                            initial={{ opacity: 0, x: 20 }}
                            whileInView={{ opacity: 1, x: 0 }}
                            transition={{ duration: 0.6, delay: 0.2 }}
                            viewport={{ once: true }}
                            className="p-6 rounded-[32px] bg-[#0C0E12] border border-white/5"
                        >
                            <h3 className="text-lg font-medium text-white mb-6">Escalation Analysis</h3>

                            <div className="grid grid-cols-2 gap-4 mb-6">
                                <div className="p-4 rounded-xl bg-red-500/5 border border-red-500/20">
                                    <div className="text-2xl font-bold text-red-400">18%</div>
                                    <div className="text-xs text-gray-500">Escalation Rate</div>
                                </div>
                                <div className="p-4 rounded-xl bg-amber-500/5 border border-amber-500/20">
                                    <div className="text-2xl font-bold text-amber-400">287</div>
                                    <div className="text-xs text-gray-500">Low Confidence</div>
                                </div>
                            </div>

                            {/* Escalation Triggers */}
                            <div className="p-4 rounded-xl bg-white/[0.02] border border-white/5">
                                <div className="text-xs text-gray-500 mb-3">Top Escalation Triggers</div>
                                <div className="space-y-3">
                                    {[
                                        { reason: "Low Confidence", count: 287, percent: 42 },
                                        { reason: "No KB Match", count: 156, percent: 23 },
                                        { reason: "Complex Query", count: 112, percent: 16 },
                                        { reason: "Customer Request", count: 89, percent: 13 },
                                        { reason: "Policy Required", count: 44, percent: 6 }
                                    ].map((item) => (
                                        <div key={item.reason}>
                                            <div className="flex justify-between text-xs mb-1">
                                                <span className="text-gray-400">{item.reason}</span>
                                                <span className="text-white">{item.count}</span>
                                            </div>
                                            <div className="h-2 rounded-full bg-white/10 overflow-hidden">
                                                <div
                                                    className="h-full rounded-full bg-gradient-to-r from-red-500/50 to-red-500"
                                                    style={{ width: `${item.percent}%` }}
                                                />
                                            </div>
                                        </div>
                                    ))}
                                </div>
                            </div>
                        </motion.div>
                    </div>
                </div>
            </section>

            {/* AI Copilot Analytics */}
            <section className="py-24 relative bg-black/50">
                <div className="max-w-[1200px] mx-auto px-6">
                    <div className="flex flex-col lg:flex-row lg:items-end justify-between mb-16 gap-8">
                        <motion.h2
                            initial={{ opacity: 0, y: 20 }}
                            whileInView={{ opacity: 1, y: 0 }}
                            transition={{ duration: 0.6 }}
                            viewport={{ once: true }}
                            className="text-4xl md:text-5xl font-medium text-white tracking-tighter leading-[1.1]"
                        >
                            AI Copilot<br />Adoption
                        </motion.h2>
                        <motion.div
                            initial={{ opacity: 0, y: 20 }}
                            whileInView={{ opacity: 1, y: 0 }}
                            transition={{ duration: 0.6, delay: 0.1 }}
                            viewport={{ once: true }}
                            className="text-xl text-gray-400 leading-relaxed max-w-lg"
                        >
                            Unique visibility into how agents use AI assistance. Track suggestion usage, edit rates, and top performers.
                        </motion.div>
                    </div>

                    {/* Metrics Grid */}
                    <div className="grid md:grid-cols-4 gap-6 mb-8">
                        {aiMetrics.map((metric, index) => (
                            <motion.div
                                key={metric.label}
                                initial={{ opacity: 0, y: 20 }}
                                whileInView={{ opacity: 1, y: 0 }}
                                transition={{ duration: 0.5, delay: index * 0.1 }}
                                viewport={{ once: true }}
                                className="p-6 rounded-[24px] bg-[#0C0E12] border border-white/5"
                            >
                                <div className="text-3xl font-bold text-white mb-1">{metric.value}</div>
                                <div className="text-sm text-white font-medium mb-1">{metric.label}</div>
                                <div className="text-xs text-gray-500">{metric.desc}</div>
                            </motion.div>
                        ))}
                    </div>

                    {/* Usage by Feature */}
                    <motion.div
                        initial={{ opacity: 0, y: 20 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        transition={{ duration: 0.6 }}
                        viewport={{ once: true }}
                        className="p-8 rounded-[32px] bg-[#0C0E12] border border-white/5"
                    >
                        <h3 className="text-lg font-medium text-white mb-6">Usage by Feature Type</h3>
                        <div className="grid md:grid-cols-3 gap-6">
                            {[
                                { feature: "Response Suggestions", generated: 8432, used: 5734, edited: 1287, rate: 68 },
                                { feature: "Conversation Summary", generated: 2847, used: 2134, edited: 423, rate: 75 },
                                { feature: "Tone Analysis", generated: 1568, used: 892, edited: 156, rate: 57 }
                            ].map((item) => (
                                <div key={item.feature} className="p-4 rounded-xl bg-white/[0.02] border border-white/5">
                                    <h4 className="text-sm text-white font-medium mb-3">{item.feature}</h4>
                                    <div className="space-y-2 text-xs">
                                        <div className="flex justify-between">
                                            <span className="text-gray-500">Generated</span>
                                            <span className="text-white">{item.generated.toLocaleString()}</span>
                                        </div>
                                        <div className="flex justify-between">
                                            <span className="text-gray-500">Used</span>
                                            <span className="text-green-400">{item.used.toLocaleString()}</span>
                                        </div>
                                        <div className="flex justify-between">
                                            <span className="text-gray-500">Edited</span>
                                            <span className="text-amber-400">{item.edited.toLocaleString()}</span>
                                        </div>
                                    </div>
                                    <div className="mt-3 pt-3 border-t border-white/5">
                                        <div className="flex items-center justify-between">
                                            <span className="text-xs text-gray-500">Usage Rate</span>
                                            <span className="text-sm font-medium text-orange-400">{item.rate}%</span>
                                        </div>
                                        <div className="h-2 rounded-full bg-white/10 overflow-hidden mt-2">
                                            <div
                                                className="h-full rounded-full bg-gradient-to-r from-orange-500 to-amber-500"
                                                style={{ width: `${item.rate}%` }}
                                            />
                                        </div>
                                    </div>
                                </div>
                            ))}
                        </div>
                    </motion.div>
                </div>
            </section>

            {/* Channel Insights */}
            <section className="py-24 relative z-10">
                <div className="max-w-[1200px] mx-auto px-6">
                    <div className="grid lg:grid-cols-2 gap-12 items-center">
                        <motion.div
                            initial={{ opacity: 0, x: -20 }}
                            whileInView={{ opacity: 1, x: 0 }}
                            transition={{ duration: 0.6 }}
                            viewport={{ once: true }}
                        >
                            <h2 className="text-4xl md:text-5xl font-medium text-white tracking-tighter mb-6 leading-[1.1]">
                                Channel<br />
                                <span className="text-gray-500">Insights</span>
                            </h2>
                            <p className="text-lg text-gray-400 leading-relaxed mb-8">
                                Understand which channels drive the most volume, AI vs agent handling per channel, and revenue attribution by source.
                            </p>

                            <div className="space-y-4">
                                {channels.map((channel) => (
                                    <div key={channel.name}>
                                        <div className="flex justify-between text-sm mb-2">
                                            <span className="text-white">{channel.name}</span>
                                            <span className="text-gray-400">{channel.value}%</span>
                                        </div>
                                        <div className="h-3 rounded-full bg-white/10 overflow-hidden">
                                            <div
                                                className="h-full rounded-full transition-all hover:opacity-80"
                                                style={{ width: `${channel.value}%`, backgroundColor: channel.color }}
                                            />
                                        </div>
                                    </div>
                                ))}
                            </div>
                        </motion.div>

                        {/* AI vs Agent Breakdown */}
                        <motion.div
                            initial={{ opacity: 0, x: 20 }}
                            whileInView={{ opacity: 1, x: 0 }}
                            transition={{ duration: 0.6, delay: 0.2 }}
                            viewport={{ once: true }}
                            className="p-8 rounded-[32px] bg-[#0C0E12] border border-white/5"
                        >
                            <h3 className="text-lg font-medium text-white mb-6">AI vs Agent Messages</h3>

                            <div className="flex items-center justify-center mb-8">
                                {/* Donut Chart Visualization */}
                                <div className="relative w-48 h-48">
                                    <svg viewBox="0 0 100 100" className="w-full h-full -rotate-90">
                                        <circle cx="50" cy="50" r="40" fill="none" stroke="rgba(255,255,255,0.1)" strokeWidth="12" />
                                        <circle
                                            cx="50" cy="50" r="40" fill="none"
                                            stroke="url(#ai-gradient)" strokeWidth="12"
                                            strokeDasharray={`${78 * 2.51} ${100 * 2.51}`}
                                            strokeLinecap="round"
                                        />
                                        <circle
                                            cx="50" cy="50" r="40" fill="none"
                                            stroke="#3B82F6" strokeWidth="12"
                                            strokeDasharray={`${22 * 2.51} ${100 * 2.51}`}
                                            strokeDashoffset={`${-78 * 2.51}`}
                                            strokeLinecap="round"
                                        />
                                        <defs>
                                            <linearGradient id="ai-gradient" x1="0%" y1="0%" x2="100%" y2="0%">
                                                <stop offset="0%" stopColor="#F97316" />
                                                <stop offset="100%" stopColor="#FBBF24" />
                                            </linearGradient>
                                        </defs>
                                    </svg>
                                    <div className="absolute inset-0 flex flex-col items-center justify-center">
                                        <div className="text-3xl font-bold text-white">78%</div>
                                        <div className="text-xs text-gray-500">AI Handled</div>
                                    </div>
                                </div>
                            </div>

                            <div className="grid grid-cols-2 gap-4">
                                <div className="p-4 rounded-xl bg-gradient-to-br from-orange-500/10 to-amber-500/10 border border-orange-500/20">
                                    <div className="flex items-center gap-2 mb-2">
                                        <Brain className="w-4 h-4 text-orange-400" />
                                        <span className="text-xs text-gray-400">AI Messages</span>
                                    </div>
                                    <div className="text-2xl font-bold text-white">24,892</div>
                                    <div className="text-xs text-orange-400">78% of total</div>
                                </div>
                                <div className="p-4 rounded-xl bg-blue-500/5 border border-blue-500/20">
                                    <div className="flex items-center gap-2 mb-2">
                                        <Users className="w-4 h-4 text-blue-400" />
                                        <span className="text-xs text-gray-400">Agent Messages</span>
                                    </div>
                                    <div className="text-2xl font-bold text-white">7,032</div>
                                    <div className="text-xs text-blue-400">22% of total</div>
                                </div>
                            </div>
                        </motion.div>
                    </div>
                </div>
            </section>

            {/* Revenue Attribution */}
            <section className="py-24 relative bg-black/50">
                <div className="max-w-[1200px] mx-auto px-6">
                    <div className="text-center mb-16">
                        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-green-500/10 border border-green-500/20 mb-4">
                            <DollarSign className="w-3 h-3 text-green-400" />
                            <span className="text-xs text-green-400 font-medium">Revenue Attribution</span>
                        </div>
                        <motion.h2
                            initial={{ opacity: 0, y: 20 }}
                            whileInView={{ opacity: 1, y: 0 }}
                            transition={{ duration: 0.6 }}
                            viewport={{ once: true }}
                            className="text-4xl md:text-5xl font-medium text-white tracking-tighter mb-4"
                        >
                            Connect Support to Revenue
                        </motion.h2>
                        <motion.p
                            initial={{ opacity: 0, y: 20 }}
                            whileInView={{ opacity: 1, y: 0 }}
                            transition={{ duration: 0.6, delay: 0.1 }}
                            viewport={{ once: true }}
                            className="text-lg text-gray-400 max-w-2xl mx-auto"
                        >
                            Automatically attribute Shopify orders to support conversations. See the real ROI of your support team.
                        </motion.p>
                    </div>

                    <motion.div
                        initial={{ opacity: 0, y: 20 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        transition={{ duration: 0.6 }}
                        viewport={{ once: true }}
                        className="grid md:grid-cols-4 gap-6"
                    >
                        {[
                            { label: "Total Revenue", value: "₹8,47,000", trend: "+18%" },
                            { label: "Conversations with Revenue", value: "892", trend: "+12%" },
                            { label: "Avg Order Value", value: "₹949", trend: "+5%" },
                            { label: "Top Channel", value: "WhatsApp", trend: "₹4.2L" }
                        ].map((stat, i) => (
                            <div key={stat.label} className="p-6 rounded-[24px] bg-[#0C0E12] border border-white/5">
                                <div className="text-sm text-gray-500 mb-2">{stat.label}</div>
                                <div className="text-2xl font-bold text-white mb-1">{stat.value}</div>
                                <div className="text-xs text-green-400">{stat.trend}</div>
                            </div>
                        ))}
                    </motion.div>
                </div>
            </section>

            {/* SLA Performance */}
            <section className="py-24 relative z-10">
                <div className="max-w-[1200px] mx-auto px-6">
                    <div className="grid lg:grid-cols-2 gap-12 items-center">
                        <motion.div
                            initial={{ opacity: 0, x: -20 }}
                            whileInView={{ opacity: 1, x: 0 satisfies number }}
                            transition={{ duration: 0.6 }}
                            viewport={{ once: true }}
                            className="p-8 rounded-[32px] bg-[#0C0E12] border border-white/5"
                        >
                            <div className="flex items-center justify-between mb-6">
                                <h3 className="text-lg font-medium text-white">SLA Performance</h3>
                                <span className="text-xs px-2 py-1 rounded bg-green-500/10 text-green-400 border border-green-500/20">Excellent</span>
                            </div>

                            <div className="text-center mb-8">
                                <div className="text-5xl font-bold text-white mb-2">96.8%</div>
                                <div className="text-sm text-gray-500">Overall SLA Compliance</div>
                            </div>

                            <div className="space-y-6">
                                <div>
                                    <div className="flex justify-between text-sm mb-2">
                                        <span className="text-gray-400">First Response Compliance</span>
                                        <span className="text-green-400">98.2%</span>
                                    </div>
                                    <div className="h-3 rounded-full bg-white/10 overflow-hidden">
                                        <div className="h-full w-[98%] rounded-full bg-gradient-to-r from-green-500 to-emerald-500" />
                                    </div>
                                </div>
                                <div>
                                    <div className="flex justify-between text-sm mb-2">
                                        <span className="text-gray-400">Resolution Compliance</span>
                                        <span className="text-green-400">95.4%</span>
                                    </div>
                                    <div className="h-3 rounded-full bg-white/10 overflow-hidden">
                                        <div className="h-full w-[95%] rounded-full bg-gradient-to-r from-green-500 to-emerald-500" />
                                    </div>
                                </div>
                            </div>

                            <div className="grid grid-cols-2 gap-4 mt-6 pt-6 border-t border-white/5">
                                <div className="p-3 rounded-xl bg-amber-500/5 border border-amber-500/20 text-center">
                                    <div className="text-lg font-bold text-amber-400">12</div>
                                    <div className="text-[10px] text-gray-500">At Risk</div>
                                </div>
                                <div className="p-3 rounded-xl bg-red-500/5 border border-red-500/20 text-center">
                                    <div className="text-lg font-bold text-red-400">3</div>
                                    <div className="text-[10px] text-gray-500">Breached</div>
                                </div>
                            </div>
                        </motion.div>

                        <motion.div
                            initial={{ opacity: 0, x: 20 }}
                            whileInView={{ opacity: 1, x: 0 }}
                            transition={{ duration: 0.6, delay: 0.2 }}
                            viewport={{ once: true }}
                        >
                            <h2 className="text-4xl md:text-5xl font-medium text-white tracking-tighter mb-6 leading-[1.1]">
                                Never miss<br />
                                <span className="text-gray-500">an SLA</span>
                            </h2>
                            <p className="text-lg text-gray-400 leading-relaxed mb-8">
                                Real-time SLA tracking with at-risk warnings and breach alerts. Goal progress bars help teams stay on target.
                            </p>

                            <div className="space-y-4">
                                {[
                                    { icon: Clock, title: "Real-Time Tracking", desc: "Live countdown timers for each SLA metric" },
                                    { icon: AlertTriangle, title: "At-Risk Warnings", desc: "Yellow alerts before SLA breach occurs" },
                                    { icon: Target, title: "Goal Progress", desc: "Visual progress toward 95% SLA target" }
                                ].map((item) => (
                                    <div key={item.title} className="flex items-start gap-4 p-4 rounded-xl bg-white/[0.02] border border-white/5">
                                        <div className="w-10 h-10 rounded-lg bg-orange-500/10 flex items-center justify-center flex-shrink-0">
                                            <item.icon className="w-5 h-5 text-orange-400" />
                                        </div>
                                        <div>
                                            <h4 className="text-white font-medium text-sm mb-1">{item.title}</h4>
                                            <p className="text-gray-500 text-xs">{item.desc}</p>
                                        </div>
                                    </div>
                                ))}
                            </div>
                        </motion.div>
                    </div>
                </div>
            </section>

            {/* Key Differentiators */}
            <section className="py-24 relative bg-black/50">
                <div className="max-w-[1200px] mx-auto px-6">
                    <div className="text-center mb-16">
                        <motion.h2
                            initial={{ opacity: 0, y: 20 }}
                            whileInView={{ opacity: 1, y: 0 }}
                            transition={{ duration: 0.6 }}
                            viewport={{ once: true }}
                            className="text-4xl md:text-5xl font-medium text-white tracking-tighter mb-4"
                        >
                            Why Enorve Analytics?
                        </motion.h2>
                    </div>

                    <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
                        {differentiators.map((item, index) => (
                            <motion.div
                                key={item.title}
                                initial={{ opacity: 0, y: 20 }}
                                whileInView={{ opacity: 1, y: 0 }}
                                transition={{ duration: 0.5, delay: index * 0.1 }}
                                viewport={{ once: true }}
                                className="group p-8 rounded-[24px] bg-[#0C0E12] border border-white/5 hover:border-orange-500/30 transition-all duration-500"
                            >
                                <div className="w-14 h-14 rounded-2xl bg-gradient-to-br from-orange-500/20 to-amber-500/20 border border-orange-500/20 flex items-center justify-center mb-6 group-hover:scale-110 transition-transform duration-500">
                                    <item.icon className="w-7 h-7 text-orange-400" />
                                </div>
                                <h3 className="text-xl font-medium text-white mb-3 tracking-tight">{item.title}</h3>
                                <p className="text-gray-400 leading-relaxed">{item.desc}</p>
                            </motion.div>
                        ))}
                    </div>
                </div>
            </section>

            {/* CTA Section */}
            <section className="max-w-4xl mx-auto px-6 pb-20 relative z-10">
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.6 }}
                    viewport={{ once: true }}
                    className="relative p-12 rounded-[32px] bg-gradient-to-br from-orange-500/10 to-amber-500/10 border border-orange-500/20 text-center overflow-hidden"
                >
                    {/* Background glow */}
                    <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_center,rgba(251,146,60,0.15),transparent_70%)]" />

                    <div className="relative z-10">
                        <h2 className="text-3xl md:text-4xl font-medium text-white mb-4 tracking-tight">
                            Ready to see everything?
                        </h2>
                        <p className="text-gray-400 mb-8 max-w-lg mx-auto">
                            Get started with Enorve and unlock comprehensive analytics for your support team.
                        </p>
                        <div className="flex flex-wrap justify-center gap-4">
                            <a href="https://app.enorve.com/">
                                <Button variant="primary" size="lg">
                                    Get Started
                                    <ArrowRight className="w-5 h-5 ml-2" />
                                </Button>
                            </a>
                            <Link to="/contact-sales">
                                <Button variant="secondary" size="lg">
                                    Talk to sales
                                </Button>
                            </Link>
                        </div>
                    </div>
                </motion.div>
            </section>

            {/* CSS for float animation */}
            <style>{`
                @keyframes float {
                    0%, 100% { transform: translateY(0px); }
                    50% { transform: translateY(-10px); }
                }
                .animate-float {
                    animation: float 3s ease-in-out infinite;
                }
            `}</style>
        </div>
    )
}
